# NXC — Limites do sistema
# Para suportar 10.000+ conexões simultâneas
# Copiado para /etc/security/limits.d/99-nxc.conf

*         soft  nofile    1000000
*         hard  nofile    1000000
root      soft  nofile    1000000
root      hard  nofile    1000000
xc_vm     soft  nofile    1000000
xc_vm     hard  nofile    1000000
xc_vm     soft  nproc     1000000
xc_vm     hard  nproc     1000000
